### ISSUE TITLE
incolumn: Separation line should start at text margin

### ISSUE THREAD

**Issue by koppor** [Jinwen-XU/mindflow#2]
The separation line of mindlfow should not start with parindent, but at 0.

This MWE should show what I mean:

```latex
\documentclass{article}
\usepackage[incolumn]{mindflow}
\usepackage{lipsum}
\begin{document}
\section{Test}
\lipsum[1]

\begin{mindflow}
	First paragraph. \lipsum[1]
	
	Second paragraph \lipsum[1]
\end{mindflow}

\end{document}
```

![image](https://user-images.githubusercontent.com/1366654/132992927-e4479710-cc9d-401f-8101-1fc585a1356e.png)

**Comment by Jinwen-XU** [comment]
Thank you for reporting this bug! It has been fixed in version 2021/09/12.
