### ISSUE TITLE
Automatic "incolumn" activation for acmart

### ISSUE THREAD

**Issue by koppor** [Jinwen-XU/mindflow#3]
According to the documentation, `incolumn` should be active when using in a two column document.

![grafik](https://user-images.githubusercontent.com/1366654/133199978-24b0209c-ea91-495c-8894-7de1abf04a6a.png)

When using [acmart](https://ctan.org/pkg/acmart), it doesn't seem to work.

MWE:

```latex
\documentclass[sigconf]{acmart}
\usepackage{mindflow}
\usepackage{lipsum}
\begin{document}
\title{Title}
\maketitle
\section{A}
\begin{mindflow}
  \lipsum[2]
\end{mindflow}
\end{document}
```

![grafik](https://user-images.githubusercontent.com/1366654/133200331-193b7f2e-7422-4acf-9b87-7183e827b145.png)

**Comment by koppor** [comment]
Similar for IEEE:

```latex
\documentclass[conference]{IEEEtran}
\usepackage{mindflow}
\usepackage{lipsum}
\begin{document}
\title{Title}
\maketitle
\section{A}
\begin{mindflow}
  \lipsum[2]
\end{mindflow}
\end{document}
```

![grafik](https://user-images.githubusercontent.com/1366654/133200443-74225cfd-1918-4443-8b97-ca9b33fae757.png)

**Comment by Jinwen-XU** [comment]
Thank you for pointing this out. Actually, by "two-column documents", I was referring to those explicitly specified by the option `twocolumn`, which is not the case in your examples. 

However, now that you requested, I have adopted a better way for detecting two-column documents in version 2021/09/15, which works pretty good for the examples you had given.

In case you encountered other problems of this package, feel free to tell me ;)

**Comment by koppor** [comment]
@Jinwen-XU Thank you for the quick action taken. I included your package in the [latex-template-generator](https://github.com/latextemplates/generator-latex-template), thus more and more persons will use it. Thank you for your work!
